export const QUESTION_TEXT = {
  title: "大语言模型 Prompt 审阅研究",
  thirdPartyInstruction:
    "在本研究中，您将作为第三方审阅者，判断一段 prompt 是否适合交给大语言模型执行相应任务，以及它可能会引导模型生成什么样的结果。",
  thirdPartyInstructionExtra:
    "请根据您对这段 prompt 本身的判断作答。",
  estimate: "预计用时：45 分钟",
  participantId: "Participant ID",
  group: "实验组别",
  groupPlaceholder: "请选择 Group A 或 Group B",
  start: "开始研究",
  resume: "继续上次研究",
  clear: "清除上次研究记录",
  appropriateness: {
    label: "您觉得这段 prompt 是否适合交给大语言模型完成当前任务？",
    minLabel: "非常不适合",
    maxLabel: "非常适合",
  },
  willingnessToUse: {
    label: "如果您是这位用户，您愿意让大语言模型按照上面的 prompt 执行吗？",
    minLabel: "非常不愿意",
    maxLabel: "非常愿意",
  },
  perceivedSafety: {
    label: "您认为将这段 prompt 交给大语言模型执行是否安全？",
    minLabel: "非常不安全",
    maxLabel: "非常安全",
  },
  perceivedReliability: {
    label: "如果大语言模型按照这段 prompt 执行，您觉得它产生可靠且令人满意的结果的可能性有多高？",
    minLabel: "非常低",
    maxLabel: "非常高",
  },
  perceivedAuthorship: {
    label: "您认为这段 prompt 更可能由谁撰写？",
    options: [
      { value: "human", label: "人类" },
      { value: "ai", label: "AI" },
      { value: "uncertain", label: "不确定" },
    ],
  },
  authorshipConfidence: {
    label: "您对上述作者身份判断有多大信心？",
    minLabel: "完全没信心",
    maxLabel: "非常有信心",
  },
  aiTagTrust: {
    label: "您在多大程度上相信页面上外部 AI 检测标签的判断？",
    minLabel: "完全不相信",
    maxLabel: "非常相信",
  },
  aiTagTitle: "外部 AI 检测标签",
  attachments: "附件：",
  attachmentHint: "点击在新标签页打开",
  revealPrompt: "查看完整 Prompt",
  promptRevealed: "Prompt 已展开",
  revealRequired: "请先点击左侧的“查看完整 Prompt”按钮，阅读完整 prompt 后再回答问题。",
  questionnaireTitle: "问卷问题",
  completeAll: "请完成当前页面所有问题后继续。",
  next: "下一步",
  oralExplanation: {
    label: "口头说明",
    instruction: "请简单聊聊您刚刚作出判断的原因，或上面 prompt 中存在的问题。",
    button: "进入下一题",
    finishButton: "结束研究",
  },
  completedTitle: "研究已完成",
  completedThanks: "感谢您完成本轮用户研究。",
  viewAnalysis: "查看结果分析",
  analysisTitle: "参与者结果分析",
  backToCompletion: "返回完成页面",
  restart: "重新开始",
} as const;
